apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: fibonacci-app
    role: web
  ports:
    - name: http
      port: 80
      targetPort: http